{{- if and .Values.ui.enabled .Values.web.enabled .Values.ui.httpRoute.enabled -}}
{{- $fullName := include "opentakserver.fullname" . -}}
{{- $svcPort := .Values.ui.service.ports.http.port -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "opentakserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
  {{- with .Values.ui.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- with .Values.ui.httpRoute.parentRefs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ui.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ui.httpRoute.rules }}
    {{- with .matches }}
    - matches:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .filters }}
      filters:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      backendRefs:
        - name: {{ include "opentakserver.uiServiceName" $ }}
          port: {{ $svcPort }}
          weight: 1
    {{- end }}
{{- end }}
