{{- if .Values.rabbitmq.enabled }}
{{- $vhost := .Values.rabbitmq.auth.vhost | default "/" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opentakserver.rabbitmqDefinitionsName" . }}
  labels:
    {{- include "opentakserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
type: Opaque
stringData:
  definitions.json: |
    {
      "vhosts": [
        {"name": {{ $vhost | quote }}}
      ],
      "exchanges": [
        {"name": "dms", "vhost": {{ $vhost | quote }}, "type": "direct", "durable": true, "auto_delete": false, "internal": false, "arguments": {}},
        {"name": "cot_parser", "vhost": {{ $vhost | quote }}, "type": "direct", "durable": true, "auto_delete": false, "internal": false, "arguments": {}},
        {"name": "chatrooms", "vhost": {{ $vhost | quote }}, "type": "direct", "durable": true, "auto_delete": false, "internal": false, "arguments": {}},
        {"name": "missions", "vhost": {{ $vhost | quote }}, "type": "topic", "durable": true, "auto_delete": false, "internal": false, "arguments": {}},
        {"name": "groups", "vhost": {{ $vhost | quote }}, "type": "topic", "durable": true, "auto_delete": false, "internal": false, "arguments": {}},
        {"name": "firehose", "vhost": {{ $vhost | quote }}, "type": "fanout", "durable": true, "auto_delete": false, "internal": false, "arguments": {}},
        {"name": "flask-socketio", "vhost": {{ $vhost | quote }}, "type": "fanout", "durable": false, "auto_delete": false, "internal": false, "arguments": {}}
      ]
    }
{{- end }}
