{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opentakserver.rabbitmqDefinitionsName" . }}
  labels:
    {{- include "opentakserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
type: Opaque
stringData:
  definitions.json: |
    {
      "vhosts": [
        {"name": {{ include "opentakserver.rabbitmqVhost" . | quote }}}
      ],
      {{- if .Values.rabbitmq.auth.existingSecret }}
      "users": [],
      "permissions": [],
      {{- else }}
      "users": [
        {"name": {{ .Values.rabbitmq.auth.username | quote }}, "password": {{ .Values.rabbitmq.auth.password | quote }}, "tags": ["administrator"]},
        {"name": "guest", "password": "guest", "tags": ["administrator"]}
      ],
      "permissions": [
        {"user": {{ .Values.rabbitmq.auth.username | quote }}, "vhost": {{ include "opentakserver.rabbitmqVhost" . | quote }}, "configure": ".*", "write": ".*", "read": ".*"},
        {"user": "guest", "vhost": {{ include "opentakserver.rabbitmqVhost" . | quote }}, "configure": ".*", "write": ".*", "read": ".*"}
      ],
      {{- end }}
      "exchanges": [
        {"name": "dms", "vhost": {{ include "opentakserver.rabbitmqVhost" . | quote }}, "type": "direct", "durable": true, "auto_delete": false, "internal": false, "arguments": {}},
        {"name": "cot_parser", "vhost": {{ include "opentakserver.rabbitmqVhost" . | quote }}, "type": "direct", "durable": true, "auto_delete": false, "internal": false, "arguments": {}},
        {"name": "chatrooms", "vhost": {{ include "opentakserver.rabbitmqVhost" . | quote }}, "type": "direct", "durable": true, "auto_delete": false, "internal": false, "arguments": {}},
        {"name": "missions", "vhost": {{ include "opentakserver.rabbitmqVhost" . | quote }}, "type": "topic", "durable": true, "auto_delete": false, "internal": false, "arguments": {}},
        {"name": "groups", "vhost": {{ include "opentakserver.rabbitmqVhost" . | quote }}, "type": "topic", "durable": true, "auto_delete": false, "internal": false, "arguments": {}},
        {"name": "firehose", "vhost": {{ include "opentakserver.rabbitmqVhost" . | quote }}, "type": "fanout", "durable": true, "auto_delete": false, "internal": false, "arguments": {}},
        {"name": "flask-socketio", "vhost": {{ include "opentakserver.rabbitmqVhost" . | quote }}, "type": "fanout", "durable": false, "auto_delete": false, "internal": false, "arguments": {}}
      ]
    }
{{- end }}
