{{- $dbSecretNeeded := and (not .Values.postgresql.enabled) (not .Values.database.uri) (not .Values.database.existingSecret.name) (or .Values.database.host .Values.database.port .Values.database.database .Values.database.username .Values.database.password) -}}
{{- $rabbitSecretNeeded := and (not .Values.rabbitmq.enabled) (not .Values.rabbitmq.external.existingSecret.name) -}}
{{- if or $dbSecretNeeded $rabbitSecretNeeded }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opentakserver.secretName" . }}
  labels:
    {{- include "opentakserver.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $dbSecretNeeded }}
  {{ .Values.database.existingSecret.keys.uri | default "uri" }}: {{ .Values.database.uri | default "" | quote }}
  {{ .Values.database.existingSecret.keys.host | default "host" }}: {{ .Values.database.host | default "" | quote }}
  {{ .Values.database.existingSecret.keys.port | default "port" }}: {{ .Values.database.port | default "" | quote }}
  {{ .Values.database.existingSecret.keys.database | default "database" }}: {{ .Values.database.database | default "" | quote }}
  {{ .Values.database.existingSecret.keys.username | default "username" }}: {{ .Values.database.username | default "" | quote }}
  {{ .Values.database.existingSecret.keys.password | default "password" }}: {{ .Values.database.password | default "" | quote }}
  {{- end }}
  {{- if $rabbitSecretNeeded }}
  {{ .Values.rabbitmq.external.existingSecret.keys.host | default "host" }}: {{ include "opentakserver.rabbitmqHost" . | quote }}
  {{ .Values.rabbitmq.external.existingSecret.keys.port | default "port" }}: {{ include "opentakserver.rabbitmqPort" . | quote }}
  {{ .Values.rabbitmq.external.existingSecret.keys.username | default "username" }}: {{ include "opentakserver.rabbitmqUsername" . | quote }}
  {{ .Values.rabbitmq.external.existingSecret.keys.password | default "password" }}: {{ include "opentakserver.rabbitmqPassword" . | quote }}
  {{ .Values.rabbitmq.external.existingSecret.keys.vhost | default "vhost" }}: {{ include "opentakserver.rabbitmqVhost" . | quote }}
  {{- end }}
{{- end }}
