{{- $dbSecretNeeded := and (not .Values.postgresql.enabled) (not .Values.database.uri) (not .Values.database.existingSecret.name) .Values.database.host -}}
{{- $rabbitSecretNeeded := and (not .Values.rabbitmq.enabled) (not .Values.rabbitmq.external.existingSecret.name) -}}
{{- if or $dbSecretNeeded $rabbitSecretNeeded }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opentakserver.secretName" . }}
  labels:
    {{- include "opentakserver.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $dbSecretNeeded }}
  db-password: {{ .Values.database.password | default "" | quote }}
  {{- end }}
  {{- if $rabbitSecretNeeded }}
  rabbitmq-password: {{ include "opentakserver.rabbitmqPassword" . | quote }}
  {{- end }}
{{- end }}
