apiVersion: v2
name: qbittorrent-exporter
description: >
  A Helm chart for qBittorrent Prometheus Exporter - exports metrics from qBittorrent to Prometheus
type: application
version: 1.0.4
# renovate: image=ghcr.io/martabal/qbittorrent-exporter
appVersion: 1.13.4
home: https://github.com/jankcloud/charts
sources:
  - https://github.com/jankcloud/charts/tree/main/charts/qbittorrent-exporter
keywords:
  - qbittorrent-exporter
  - qbittorrent
  - prometheus
  - exporter
maintainers:
  - name: jankcloud
    url: https://github.com/jankcloud
