apiVersion: v2
name: radarr
description: A Helm chart for deploying Radarr
type: application
version: 1.0.5
appVersion: 6.0.4@sha256:a360633a3682d41e96f71a07ff36ecbdf2394a9628465b84b0a8437087715b41
home: https://radarr.video
sources:
  - https://github.com/jankcloud/charts/tree/main/charts/radarr
  - https://github.com/Radarr/Radarr
keywords:
  - radarr
  - servarr
  - pvr
  - usenet
  - bittorrent
maintainers:
  - name: jankcloud
    url: https://github.com/jankcloud
dependencies:
  - name: arr-common
    version: "0.1.0"
    repository: "https://jankcloud.github.io/charts"
    import-values:
      - defaults
