# yaml-language-server: $schema=values.schema.json
image:
  repository: ghcr.io/linuxserver/radarr
  tag: 6.0.4@sha256:a360633a3682d41e96f71a07ff36ecbdf2394a9628465b84b0a8437087715b41
  pullPolicy: IfNotPresent

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

strategy:
  type: Recreate

env:
  PUID: "1000"
  PGID: "1000"
  TZ: "America/New_York"

service:
  type: ClusterIP
  port: 7878
  annotations: {}

persistence:
  config:
    enabled: false
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 2Gi
    volumeName: ""

additionalVolumes: []
  # - name: tv
  #   mountPath: /tv
  #   existingClaim: ""
  #   readOnly: false
  #   pvc:
  #     accessMode: ReadWriteMany
  #     size: 5Ti
  #     storageClass: nfs-client

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

probes:
  liveness:
    httpGet:
      path: /ping
      port: http
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 5
  readiness:
    httpGet:
      path: /ping
      port: http
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 1Gi

serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  labels: {}
  annotations: {}

exportarr:
  enabled: false
  image:
    repository: ghcr.io/onedr0p/exportarr
    tag: v2.3.0@sha256:af535d94061cf97a52e1661945ffba78c03f9443eae7c0da1a80a5a4be56b520
    pullPolicy: IfNotPresent
  port: 9707
  env:
    URL: "http://localhost:7878"
    APIKEY: ""

gluetun:
  enabled: false
  image:
    repository: ghcr.io/qdm12/gluetun
    tag: latest@sha256:2393617bfc57629e28ca55db3174e6907c7aa0796af3da98fa034778ad1d99e5
    pullPolicy: IfNotPresent
  env: {}
  existingSecret: ""

nodeSelector: {}
tolerations: []
affinity: {}

initContainers: []
sidecars: []
extraVolumes: []
extraVolumeMounts: []
