apiVersion: v2
name: qui
description: >
  A Helm chart for Qui
type: application
version: 1.2.3
# renovate: image=ghcr.io/autobrr/qui
appVersion: 1.14.1
home: https://github.com/autobrr/qui
sources:
  - https://github.com/jankcloud/charts/tree/main/charts/qui
keywords:
  - qui
  - qbittorrent
  - cross-seed
maintainers:
  - name: jankcloud
    url: https://github.com/jankcloud
