apiVersion: v2
name: servarr-stack
description: >
  A Helm chart for deploying the Servarr stack
type: application
version: 0.12.0
appVersion: 1.0.0
home: https://github.com/jankcloud/charts
sources:
  - https://github.com/jankcloud/charts/tree/main/charts/servarr-stack
  - https://github.com/jankcloud/charts/tree/main/charts/radarr
  - https://github.com/jankcloud/charts/tree/main/charts/sonarr
keywords:
  - servarr
  - radarr
  - sonarr
  - bazarr
  - lidarr
  - cleanuparr
  - prowlarr
maintainers:
  - name: jankcloud
    url: https://github.com/jankcloud
dependencies:
  - name: radarr
    version: "1.4.0"
    repository: "https://jankcloud.github.io/charts"
    condition: radarr.enabled
  - name: sonarr
    version: "1.4.0"
    repository: "https://jankcloud.github.io/charts"
    condition: sonarr.enabled
  - name: bazarr
    version: "1.3.0"
    repository: "https://jankcloud.github.io/charts"
    condition: bazarr.enabled
  - name: lidarr
    version: "1.2.0"
    repository: "https://jankcloud.github.io/charts"
    condition: lidarr.enabled
  - name: cleanuparr
    version: "1.2.2"
    repository: "https://jankcloud.github.io/charts"
    condition: cleanuparr.enabled
  - name: prowlarr
    version: "1.5.0"
    repository: "https://jankcloud.github.io/charts"
    condition: prowlarr.enabled
