apiVersion: v2
name: prowlarr
description: >
  A Helm chart for deploying Prowlarr
type: application
version: 1.3.0
# renovate: image=ghcr.io/linuxserver/prowlarr
appVersion: 2.3.0
home: https://prowlarr.com
sources:
  - https://github.com/jankcloud/charts/tree/main/charts/prowlarr
  - https://github.com/Prowlarr/Prowlarr
keywords:
  - prowlarr
  - servarr
  - indexer
  - usenet
  - bittorrent
maintainers:
  - name: jankcloud
    url: https://github.com/jankcloud
dependencies:
  - name: arr-common
    version: "0.1.2"
    repository: "https://jankcloud.github.io/charts"
    import-values:
      - defaults
