name: Publish Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: chart_release
  cancel-in-progress: false
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "JankBot"
          git config user.email "jankbot@users.noreply.github.com"

      - name: Add jankcloud Helm repository
        run: helm repo add jankcloud https://jankcloud.github.io/charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        with:
          charts_dir: charts
          skip_existing: true
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
